server:
  port: 8030
spring:
  datasource:
    url: jdbc:mysql://localhost:3303/ingredient-database
    username: pet-food-recipe-user
    password: mysql
  jpa:
    hibernate:
      ddl-auto: update
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: true
    defer-datasource-initialization: true