server:
  port: 8020
spring:
  datasource:
    url: jdbc:mysql://localhost:3302/pet-database
    username: pet-food-recipe-user
    password: mysql
  jpa:
    hibernate:
      ddl-auto: update
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: true
    defer-datasource-initialization: true

application:
  config:
    user-url: http://localhost:8010/v1/users